### ISSUE TITLE
Error installing httpuv on centos5

### ISSUE THREAD

**Issue by dchiu911** [rstudio/httpuv#218]
I ran 
```r
withr::with_makevars(
  c(PKG_CPPFLAGS="-DDEBUG_TRACE -DDEBUG_THREAD -UNDEBUG"), {
    devtools::install_github("rstudio/httpuv")
  }, assignment = "+="
)
```
and installation failed with on my centos5 machine with the following printouts at the end:
```make
src/unix/linux-core.c:88:22: error: ‘EPOLL_CLOEXEC’ undeclared (first use in this function)
   fd = epoll_create1(EPOLL_CLOEXEC);
                      ^
src/unix/linux-core.c:88:22: note: each undeclared identifier is reported only once for each function it appears in
src/unix/linux-core.c: In function ‘uv__io_poll’:
src/unix/linux-core.c:279:12: warning: implicit declaration of function ‘epoll_pwait’ [-Wimplicit-function-declaration]
     nfds = epoll_pwait(loop->backend_fd,
            ^
make[1]: *** [Makefile:2701: src/unix/libuv_la-linux-core.lo] Error 1
make[1]: Leaving directory '/tmp/RtmpeFPr04/R.INSTALL3c437cad991/httpuv/src/libuv'
make: *** [Makevars:74: libuv/.libs/libuv.a] Error 2
ERROR: compilation failed for package ‘httpuv’
```

**Comment by wch** [comment]
Sorry, we don't have plans to support Centos 5, since it's so old and no longer supported.

httpuv uses libuv, and it [supports Linux kernel 2.6.32 and above](https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md). However [RHEL 5](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#RHEL_5) (and therefore Centos 5) uses 2.6.18

Also, for reference, here's mention in the libuv chat logs about Centos 5 and EPOLL_CLOEXEC:
http://logs.libuv.org/node-build/2018-11-20#21:39:08.876
