### ISSUE TITLE
Installation of "httpuv" package never ends

### ISSUE THREAD

**Issue by bma8** [rstudio/httpuv#281]
I am trying to install "httpuv"  having R version 4.0.2 (2020-06-22) installed on Ubuntu 18.04.4 LTS, bionic (on AWS AMI). 
After installing R, I did
`sudo -i R` 
`install.packages("Rcpp")`
which was successfully installed. 
and then when I do
`install.packages("httpuv")`
it starts well and after quite a long time when everything seems to be correctly installed, it seems it wants to complete something, but it never ends! The last parts of the printing outputs are: 
```........
In file included from /usr/local/lib/R/site-library/BH/include/boost/shared_ptr.hpp:17:0,
                 from httprequest.cpp:2:
/usr/local/lib/R/site-library/BH/include/boost/smart_ptr/shared_ptr.hpp: In member function ‘boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::auto_ptr<_Up>&&)’:
/usr/local/lib/R/site-library/BH/include/boost/smart_ptr/shared_ptr.hpp:578:38: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
         this_type( static_cast< std::auto_ptr<Y> && >( r ) ).swap( *this );
                                      ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /usr/local/lib/R/site-library/BH/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/local/lib/R/site-library/BH/include/boost/get_pointer.hpp:14,
                 from /usr/local/lib/R/site-library/BH/include/boost/bind/mem_fn.hpp:25,
                 from /usr/local/lib/R/site-library/BH/include/boost/mem_fn.hpp:22,
                 from /usr/local/lib/R/site-library/BH/include/boost/bind/bind.hpp:26,
                 from /usr/local/lib/R/site-library/BH/include/boost/bind.hpp:22,
                 from httprequest.cpp:1:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;

```

BTW, after this, the EC2 instance "Status Checks" will no longer show green/ok (2/2 checks passed) and the website is not accessible. I need to reboot the EC2 instance (Linux).

Your help will be greatly appreciated (please let me know if an alternative way, for example, installing by using `sudo apt-get install -y ...` or something like that will work). My ultimate goal is to install shiny.

**Comment by wch** [comment]
A t2.micro has 1GB of memory, and I've definitely encountered cases where that's not sufficient to compile httpuv, when other stuff (like RStudio) is running.

**Comment by moodymudskipper** [comment]
@wch

It's a situation that happens quite a lot it seems, I found several internet discussions on it, since AWS 's free server has only 1GB. It's a pity that we can't use shiny on the free AWS server because of the memory needed for the installation of this dependency.

There's no way to tweak something so it takes less memory ? 

If not could we have a clearer information of the memory issue ? The installation output is very intimidating and it took me a couple hours to try to debug it until I realized there was nothing I could do, it'd be nice to help next users spare this time.

**Comment by wch** [comment]
As far as I know, there's no straightforward way to change things so that compilation takes more memory. The system's compiler just expects there to be enough memory.

Some possible solutions: You could precompile a binary R package on a separate computer, store it somewhere, and install that. Or you could install the system packages for various R packages (for Ubuntu and Debian, it's `r-cran-httpuv`). Or you could allocate some virtual memory in your VM.

In the future we'll move to C++11, and that will probably let us remove Boost headers. It's possible that will reduce the memory footprint, but I don't know for sure.
