### ISSUE TITLE
Error installing httpuv on RStudio Server 

### ISSUE THREAD

**Issue by msoehren** [rstudio/httpuv#293]
I am trying to install "rtweet" on a RStudio Server and httpuv can't be installed. Here is the error code I am receiving: 

Thanks in advance for any input on this. 
```
* installing *source* package ‘httpuv’ ...
** package ‘httpuv’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG -Ilibuv/include -pthread  -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include" -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/later/include"   -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports-legacy.cpp -o RcppExports-legacy.o
g++  -I/usr/share/R/include -DNDEBUG -Ilibuv/include -pthread  -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include" -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/later/include"   -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
g++  -I/usr/share/R/include -DNDEBUG -Ilibuv/include -pthread  -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include" -I"/home/malte/R/x86_64-pc-linux-gnu-library/3.3/later/include"   -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c callback.cpp -o callback.o
In file included from /home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/bind/mem_fn.hpp:25:0,
                 from /home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/mem_fn.hpp:22,
                 from /home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/function/detail/prologue.hpp:18,
                 from /home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/function.hpp:30,
                 from callback.h:4,
                 from callback.cpp:1:
/home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/get_pointer.hpp:48:40: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                        ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/function/function_base.hpp:16,
                 from /home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/function/detail/prologue.hpp:17,
                 from /home/malte/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/function.hpp:30,
                 from callback.h:4,
                 from callback.cpp:1:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
```

**Comment by abnercasallo** [comment]
I'm using AWS to deploy my shiny and I have the same problem, I read that It's related to memory, but I don't know a good solution. Someone knows one?

**Comment by jcheng5** [comment]
Those are just warnings, you'll have to post more of the log to show why it's actually not installing (if indeed it's not).

**Comment by abnercasallo** [comment]
@jcheng5 The problem is that It never ends (it stops). I think It's similar to this issue : https://github.com/rstudio/httpuv/issues/281

**Comment by jcheng5** [comment]
Oh, if it terminates right there then it is an out of memory issue. You can either use an EC2 instance class that has more memory, or set up [a swap file of a few GB](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-memory-swap-file/), or install from binary instead of source using [RStudio Package Manager](https://packagemanager.rstudio.com/client/#/repos/2/overview) (on that page, under "You can also choose to use source or binary packages", click "Binary", then on the following line select your Linux distribution, then jump down to "Outside of RStudio").

**Comment by fvg98** [comment]
Just wanted to add on this for future reference, got the thing to work.

@abnercasallo  states that his end goal was to install shiny onto a 1 core, 1GB RAM EC2. For this, he tried to install httpuv beforehand, as his error message pointed him towards it. OP was hoping that installing it first would then allow him to install shiny onto the VM. I know because the exact thing happened to me, and I tried the same thing (among others) too. I want to confirm that a t2.small (which is just one xtra GB) is enough to complete the installation of shiny and shiny server. Just stop the instance, upgrade it temporarily, do the work, stop again, and revert to the original instance.
